/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_xmtj_bpgdecoder_DecoderWrapper
#define _Included_com_xmtj_bpgdecoder_DecoderWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Method:    fetchDecodedBufferSize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xmtj_bpgdecoder_DecoderWrapper_init
        (JNIEnv *, jclass, jstring, jstring,jstring);

/*
 * Method:    fetchDecodedBufferSize
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_xmtj_bpgdecoder_DecoderWrapper_fetchDecodedBufferSize
        (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Method:    decodeBufferV2
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xmtj_bpgdecoder_DecoderWrapper_decodeBufferV2
        (JNIEnv *, jclass, jbyteArray, jint);




#ifdef __cplusplus
}
#endif
#endif
